name: "Build Push Docker"

on:
  push:
    # run only against tags
    tags:
      - "*"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # ENV: prod
  # SSH_HOST: 54.169.248.77
  # SSH_USER: ubuntu

permissions:
  contents: write
  packages: write
  id-token: write
  # issues: write

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker meta
        id: meta-app
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./cloud-setup/container/container-plain-plain/
          file: Dockerfile
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
